[package]
name = "rustbasic-cli"
version = "0.0.16"
edition = "2024"
description = "CLI tool for the RustBasic Framework."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/herisvan321/rustbasic"
repository = "https://github.com/herisvan321/rustbasic"
documentation = "https://github.com/herisvan321/rustbasic"
keywords = ["rustbasic", "framework", "cli", "scaffolding", "orm"]
categories = ["development-tools", "command-line-utilities", "web-programming"]

[dependencies]
tokio = { version = "1.52.1", features = ["full"] }
colored = "3.0"
dotenvy = "0.15.7"
chrono = { version = "0.4.39", features = ["serde"] }
sea-orm = { version = "1.1.4", features = ["runtime-tokio-rustls", "sqlx-sqlite", "sqlx-mysql", "macros", "with-chrono"], default-features = false }
sea-orm-migration = { version = "1.1.4", features = ["runtime-tokio-rustls", "sqlx-sqlite", "sqlx-mysql"], default-features = false }
regex = "1.10"
rand = "0.10.1"
base64 = "0.22.1"

[[bin]]
name = "rustbasic"
path = "src/main.rs"



