[package]
name = "rustbasic-cli"
version = "0.0.32"
edition = "2024"
description = "CLI tool for the RustBasic Framework."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/herisvan321/rustbasic"
repository = "https://github.com/herisvan321/rustbasic"
documentation = "https://github.com/herisvan321/rustbasic"
keywords = ["rustbasic", "framework", "cli", "scaffolding", "web"]
categories = ["development-tools", "command-line-utilities", "web-programming"]

[dependencies]
rustbasic-core = { version = "0.1",  features = ["regex"] }

[features]
default = ["sqlite", "mysql"]
sqlite = ["rustbasic-core/sqlite"]
sqlite-bundled = ["rustbasic-core/sqlite-bundled"]
mysql = ["rustbasic-core/mysql"]

[[bin]]
name = "rustbasic"
path = "src/main.rs"
